all:
	cd 1_Intro; make
	cd 2_Mapping; make
	cd 3_Tertiary; make
	cd 4_Browsers; make

clean:
	cd 1_Intro; make clean
	cd 2_Mapping; make clean
	cd 3_Tertiary; make clean
	cd 4_Browsers; make clean
	
	